package endereco.visao;

/**
 * @author Carlos Alexandre
 */
public class JMenu extends javax.swing.JFrame {

    /** Creates new form JMenu */
    public JMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastra = new javax.swing.JMenu();
        mnuEstado = new javax.swing.JMenuItem();
        mnuCidade = new javax.swing.JMenuItem();
        mnuBairro = new javax.swing.JMenuItem();
        mnuLogradouro = new javax.swing.JMenuItem();
        mnuTipoLogradouro = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenu();
        mnuEstados = new javax.swing.JMenuItem();
        mnuCidades = new javax.swing.JMenuItem();
        mnuBairros = new javax.swing.JMenuItem();
        mnuLogs = new javax.swing.JMenuItem();
        mnuTiposLog = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuCadastra.setText("Cadastra");

        mnuEstado.setText("Estado");
        mnuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstadoActionPerformed(evt);
            }
        });
        mnuCadastra.add(mnuEstado);

        mnuCidade.setText("Cidade");
        mnuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCidadeActionPerformed(evt);
            }
        });
        mnuCadastra.add(mnuCidade);

        mnuBairro.setText("Bairro");
        mnuBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBairroActionPerformed(evt);
            }
        });
        mnuCadastra.add(mnuBairro);

        mnuLogradouro.setText("Logradouro");
        mnuLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogradouroActionPerformed(evt);
            }
        });
        mnuCadastra.add(mnuLogradouro);

        mnuTipoLogradouro.setText("Tipo Logradouro");
        mnuTipoLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoLogradouroActionPerformed(evt);
            }
        });
        mnuCadastra.add(mnuTipoLogradouro);

        jMenuBar1.add(mnuCadastra);

        mnuConsulta.setText("Consulta");

        mnuEstados.setText("Estados");
        mnuEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstadosActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuEstados);

        mnuCidades.setText("Cidades");
        mnuCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCidadesActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuCidades);

        mnuBairros.setText("Bairros");
        mnuBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBairrosActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuBairros);

        mnuLogs.setText("Logradouros");
        mnuLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogsActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuLogs);

        mnuTiposLog.setText("Tipos Logradouro");
        mnuTiposLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTiposLogActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuTiposLog);

        jMenuBar1.add(mnuConsulta);

        mnuSair.setText("Sair");
        mnuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstadoActionPerformed
        // TODO add your handling code here:
        CadastraEstado estado = new CadastraEstado(this, true);
        estado.setVisible(true);
    }//GEN-LAST:event_mnuEstadoActionPerformed

    private void mnuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCidadeActionPerformed
        // TODO add your handling code here:
        CadastraCidade cidade = new CadastraCidade(this, true);
        cidade.setVisible(true);
    }//GEN-LAST:event_mnuCidadeActionPerformed

    private void mnuBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBairroActionPerformed
        // TODO add your handling code here:
        CadastraBairro bairro = new CadastraBairro(this, true);
        bairro.setVisible(true);
    }//GEN-LAST:event_mnuBairroActionPerformed

    private void mnuLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogradouroActionPerformed
        // TODO add your handling code here:
        CadastraLog log = new CadastraLog(this, true);
        log.setVisible(true);
    }//GEN-LAST:event_mnuLogradouroActionPerformed

    private void mnuTipoLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoLogradouroActionPerformed
        // TODO add your handling code here:
        CadastraTipoLog tipo = new CadastraTipoLog(this, true);
        tipo.setVisible(true);
    }//GEN-LAST:event_mnuTipoLogradouroActionPerformed

    private void mnuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSairMouseClicked

    private void mnuEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstadosActionPerformed
        // TODO add your handling code here:
        ConsultaEstado estado = new ConsultaEstado(this, true);
        estado.setVisible(true);
    }//GEN-LAST:event_mnuEstadosActionPerformed

private void mnuCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCidadesActionPerformed
// TODO add your handling code here:
    ConsultaCidade cidade = new ConsultaCidade(this, true);
    cidade.setVisible(true);
}//GEN-LAST:event_mnuCidadesActionPerformed

private void mnuBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBairrosActionPerformed
    // TODO add your handling code here:
    ConsultaBairro bairro = new ConsultaBairro(this, true);
    bairro.setVisible(true);
}//GEN-LAST:event_mnuBairrosActionPerformed

private void mnuLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogsActionPerformed
// TODO add your handling code here:
    ConsultaLogradouro logradouro = new ConsultaLogradouro(this, true);
    logradouro.setVisible(true);
}//GEN-LAST:event_mnuLogsActionPerformed

private void mnuTiposLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTiposLogActionPerformed
    // TODO add your handling code here:
    ConsultaTipoLog tipoLog = new ConsultaTipoLog(this, true);
    tipoLog.setVisible(true);
}//GEN-LAST:event_mnuTiposLogActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuBairro;
    private javax.swing.JMenuItem mnuBairros;
    private javax.swing.JMenu mnuCadastra;
    private javax.swing.JMenuItem mnuCidade;
    private javax.swing.JMenuItem mnuCidades;
    private javax.swing.JMenu mnuConsulta;
    private javax.swing.JMenuItem mnuEstado;
    private javax.swing.JMenuItem mnuEstados;
    private javax.swing.JMenuItem mnuLogradouro;
    private javax.swing.JMenuItem mnuLogs;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenuItem mnuTipoLogradouro;
    private javax.swing.JMenuItem mnuTiposLog;
    // End of variables declaration//GEN-END:variables
}
